### ISSUE TITLE
Login using Shibboleth and via IP not working

### ISSUE THREAD

**Issue by jmechnich** [Ingo-FP-Angel/plugin.video.filmfriend.de#13]
When I was trying to login to filmfriend using my credentials for the "Universität Mannheim", I got the following error:

```
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'KeyError'>
Error Contents: 'location'
Traceback (most recent call last):
  File "/Users/mechnich/Library/Application Support/Kodi/addons/plugin.video.filmfriend.de/default.py", line 52, in <module>
    login.pick()
  File "/Users/mechnich/Library/Application Support/Kodi/addons/plugin.video.filmfriend.de/resources/lib/login.py", line 175, in pick
    firstRedirectUrl = response.headers['Location']
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
File "/Users/mechnich/Library/Application Support/Kodi/addons/script.module.requests/lib/requests/structures.py", line 52, in __getitem__
  return self._store[key.lower()][1]
         ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'location'
-->End of Python script error report<--
```

After looking at the code it seems that login via Shibboleth is not supported (and probably also not that easy to implement). However, my university also supports login via IP if the host uses the university's network.

Unfortunately, at least in this case, sign in via IP is listed as a *delegated* login method and *external* takes precedence.

It would already be helpful if it was possible to explicitly select one of the login methods during login.

The following is the provider info for the "Universität Mannheim" (tenant id bffebeed-05f8-40bf-937d-aeada3e8a2b7):

```yaml
{
  'local': None,
  'delegated': [
    {
      'provider': 'ff4da517-dd2a-4c50-936d-f38d155cc242',
      'displayName': 'Sign in via IP',
      'providerKind': 'Ip',
      'information': 'Sign in via IP',
      'userNameKind': None
    }
  ],
  'external': [
    {
      'provider': '15647c4b-2f6e-45c1-9643-c3c8e9ab17d1',
      'displayName': 'Sign in via Shibboleth',
      'providerKind': 'Shibboleth'
    }
  ]
}
```

**Comment by jmechnich** [comment]
I can confirm that I am able to complete the login process when forcing the authentication type to "delegated". However, at least on my Debian 12 desktop at the university, Kodi segfaults in a library from inputstream.adaptive when starting playback of a random movie from filmfriend. 😞

[kodi_crashlog-20240416_214032.log](https://github.com/Ingo-FP-Angel/plugin.video.filmfriend.de/files/15001927/kodi_crashlog-20240416_214032.log)

**Comment by Ingo-FP-Angel** [comment]
I've created a beta prerelease at https://github.com/Ingo-FP-Angel/plugin.video.filmfriend.de/releases/tag/1.0.11-beta.1

This will automatically use IP based login if that's the only supported way of authentication presented by the library.
In addition the addon will show an error if the library only uses providers that are not supported yet instead of simply crashing.

**Comment by Ingo-FP-Angel** [comment]
About the crash on playback, I think I can't really help. The only clue to me it seems is this error

``` 
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init 
```

but it might not even be the cause of the crash.

Maybe it helps to update the inputstream.adaptive addon. The log shows version 20.3.2 and the most recent one is 20.3.18.

**Comment by jmechnich** [comment]
> I've created a beta prerelease at https://github.com/Ingo-FP-Angel/plugin.video.filmfriend.de/releases/tag/1.0.11-beta.1
> 
> This will automatically use IP based login if that's the only supported way of authentication presented by the library. In addition the addon will show an error if the library only uses providers that are not supported yet instead of simply crashing.

Thanks, this seems to work!

**Comment by jmechnich** [comment]
> About the crash on playback, I think I can't really help. The only clue to me it seems is this error
> 
> ```
> libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init 
> ```
> 
> but it might not even be the cause of the crash.
> 
> Maybe it helps to update the inputstream.adaptive addon. The log shows version 20.3.2 and the most recent one is 20.3.18.

The libva error should not be relevant: a number of drivers are tested consecutively and this one does not fit my graphics card. Generally, libva works fine.

**Comment by Ingo-FP-Angel** [comment]
Thanks for testing. I've released v1.0.11 with the changes plus the usual meta data updates.

In order to support Shibboleth, would you be willing to capture the network traffic with the browser development tools while you're performing a login to the filmfriend web page? Be sure to remove username/password before sending the captured data.
